version: '2'

services:
  app:
    image: 'marven:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgresDB
      - SPRING_DATASOURCE_USERNAME=postgresUser
      - SPRING_DATASOURCE_PASSWORD=postgresPW
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - 5455:5432
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
      - POSTGRES_DB=postgresDB